name: workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile linearAlgebra.cpp
        run: g++ linearAlgebra.cpp -o linearAlgebra.exe

      - name: Run app.exe
        run: ./linearAlgebra.exe
  image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install opencv
        run: pip install opencv-python

      - name: Run createImage.py
        run: python3 createImage.py
  
      - name: Compile printAsHex.cpp
        run: g++ printAsHex.cpp -o printAsHex.exe

      - name: Run printAsHex.exe
        run: ./printAsHex.exe
